"""Create a Spotify playlist from a finished MixID job.

User-initiated flow:
  1. After tracklist appears, user clicks "Add to Spotify".
  2. Browser opens /spotify/login?job_id=... → redirects to Spotify auth.
  3. Spotify redirects back to /spotify/callback with an auth code.
  4. Server exchanges code → access token → creates a private playlist
     in the user's Spotify with all identified tracks, then redirects
     back to the PWA with the playlist URL.

Requires (in .env):
  SPOTIFY_CLIENT_ID
  SPOTIFY_CLIENT_SECRET
  SPOTIFY_REDIRECT_URI   (default: http://localhost:8000/spotify/callback)

The user must also REGISTER the redirect URI in their Spotify Developer
dashboard for the OAuth flow to succeed.
"""
from __future__ import annotations

import logging
import os
from dataclasses import dataclass

import config

log = logging.getLogger(__name__)


DEFAULT_REDIRECT_URI = "http://localhost:8000/spotify/callback"
PLAYLIST_NAME_PREFIX = "MixID — "
PLAYLIST_DESCRIPTION = "Auto-generated by MixID (https://github.com/Skappy-Yolo/mixid)"


def redirect_uri() -> str:
    return os.getenv("SPOTIFY_REDIRECT_URI", DEFAULT_REDIRECT_URI)


def is_configured() -> bool:
    return bool(config.SPOTIFY_CLIENT_ID and config.SPOTIFY_CLIENT_SECRET)


def _auth_manager(state: str = ""):
    from spotipy.oauth2 import SpotifyOAuth
    return SpotifyOAuth(
        client_id=config.SPOTIFY_CLIENT_ID,
        client_secret=config.SPOTIFY_CLIENT_SECRET,
        redirect_uri=redirect_uri(),
        scope="playlist-modify-private playlist-modify-public",
        state=state,
        cache_handler=None,  # we don't persist tokens — one-shot use
        open_browser=False,
    )


def build_login_url(job_id: str) -> str:
    """The Spotify authorize URL the user should be redirected to."""
    return _auth_manager(state=job_id).get_authorize_url()


@dataclass
class PlaylistResult:
    playlist_id: str
    playlist_url: str
    tracks_added: int
    tracks_unmatched: list[str]   # 'Artist - Title' strings we couldn't find on Spotify


def exchange_and_create_playlist(
    code: str,
    tracks: list[dict],
    name_suffix: str = "",
) -> PlaylistResult:
    """Exchange the OAuth code for a token, then create a playlist with the tracks.

    `tracks` is a list of dicts with at least 'artist' and 'title' keys
    (same shape as the PWA result payload).
    """
    import spotipy

    auth = _auth_manager()
    token_info = auth.get_access_token(code, as_dict=True, check_cache=False)
    if not token_info or "access_token" not in token_info:
        raise RuntimeError("Spotify token exchange failed.")
    sp = spotipy.Spotify(auth=token_info["access_token"])

    user = sp.current_user()
    if not user or "id" not in user:
        raise RuntimeError("Could not read Spotify user profile.")

    playlist_name = f"{PLAYLIST_NAME_PREFIX}{name_suffix}".strip()[:100] or "MixID Tracklist"
    playlist = sp.user_playlist_create(
        user=user["id"],
        name=playlist_name,
        public=False,
        description=PLAYLIST_DESCRIPTION,
    )

    track_uris: list[str] = []
    unmatched: list[str] = []
    for t in tracks:
        artist = (t.get("artist") or "").strip()
        title = (t.get("title") or "").strip()
        if not title:
            continue
        # Spotify search: prefer artist+title; fall back to title alone
        query = f'track:"{title}" artist:"{artist}"' if artist else f'track:"{title}"'
        try:
            results = sp.search(q=query, type="track", limit=1)
        except Exception as e:
            log.warning("Spotify search failed for %r: %s", query, e)
            unmatched.append(f"{artist} - {title}".strip(" -"))
            continue
        items = (results.get("tracks") or {}).get("items") or []
        if not items:
            # Loosen the query
            try:
                loose = sp.search(q=f"{artist} {title}".strip(), type="track", limit=1)
                items = (loose.get("tracks") or {}).get("items") or []
            except Exception:
                items = []
        if not items:
            unmatched.append(f"{artist} - {title}".strip(" -"))
            continue
        track_uris.append(items[0]["uri"])

    # Spotify limits add_items to 100 per call
    added = 0
    for i in range(0, len(track_uris), 100):
        chunk = track_uris[i : i + 100]
        sp.playlist_add_items(playlist["id"], chunk)
        added += len(chunk)

    return PlaylistResult(
        playlist_id=playlist["id"],
        playlist_url=(playlist.get("external_urls") or {}).get("spotify", ""),
        tracks_added=added,
        tracks_unmatched=unmatched,
    )
