"""Create a Spotify playlist on the HOST's account (one-time setup).

Architecture choice: instead of every user authorizing Spotify (which
means each user has to log in + we have to register their callback),
the HOST (you, the deployer) authorizes Spotify ONCE during setup.

Setup (you, once):
    python -m mixid.web.spotify_setup
  → opens browser → you log in → script prints a refresh token
  → paste that as SPOTIFY_HOST_REFRESH_TOKEN in .env

Runtime (every user):
  → User clicks "Add to Spotify" on their tracklist
  → Server uses your refresh token to mint an access token
  → Creates a PUBLIC playlist on your Spotify account with the tracks
  → User gets a clickable Spotify URL — no login on their end

Trade-off you accept: every playlist appears on YOUR public Spotify
profile under @sarsat (or whatever your handle is). For a portfolio
project that's a feature, not a bug — adds discoverability.
"""
from __future__ import annotations

import logging
import os
from dataclasses import dataclass

import config

log = logging.getLogger(__name__)


DEFAULT_REDIRECT_URI = "http://localhost:8000/spotify/callback"
PLAYLIST_DESCRIPTION = "Auto-generated by MixID (https://github.com/Skappy-Yolo/mixid)"
PLAYLIST_NAME_PREFIX = "MixID — "
HOST_SCOPES = "playlist-modify-public playlist-modify-private"


class NoHostConfigured(RuntimeError):
    """Server hasn't been Spotify-authenticated yet (run spotify_setup)."""


@dataclass
class PlaylistResult:
    playlist_id: str
    playlist_url: str
    tracks_added: int
    tracks_unmatched: list[str]


def redirect_uri() -> str:
    return os.getenv("SPOTIFY_REDIRECT_URI", DEFAULT_REDIRECT_URI)


def is_configured() -> bool:
    """True when the public 'Add to Spotify' button should appear in the UI."""
    return bool(
        config.SPOTIFY_CLIENT_ID
        and config.SPOTIFY_CLIENT_SECRET
        and config.SPOTIFY_HOST_REFRESH_TOKEN
    )


def _auth_manager():
    from spotipy.oauth2 import SpotifyOAuth
    return SpotifyOAuth(
        client_id=config.SPOTIFY_CLIENT_ID,
        client_secret=config.SPOTIFY_CLIENT_SECRET,
        redirect_uri=redirect_uri(),
        scope=HOST_SCOPES,
        cache_handler=None,
        open_browser=False,
    )


def get_host_client():
    """Spotipy client authenticated as the host (you). Refreshes on demand."""
    import spotipy
    if not config.SPOTIFY_HOST_REFRESH_TOKEN:
        raise NoHostConfigured(
            "No Spotify host token yet. Run `python -m mixid.web.spotify_setup` once "
            "to authorize, then put SPOTIFY_HOST_REFRESH_TOKEN in your .env."
        )
    auth = _auth_manager()
    token_info = auth.refresh_access_token(config.SPOTIFY_HOST_REFRESH_TOKEN)
    if not token_info or "access_token" not in token_info:
        raise NoHostConfigured(
            "Spotify refresh failed — the saved refresh token may have been "
            "revoked. Re-run `python -m mixid.web.spotify_setup`."
        )
    return spotipy.Spotify(auth=token_info["access_token"])


def create_playlist_on_host(
    tracks: list[dict], name_suffix: str = ""
) -> PlaylistResult:
    """Create a public playlist on the host's Spotify with the identified tracks."""
    sp = get_host_client()
    user = sp.current_user()
    if not user or "id" not in user:
        raise RuntimeError("Could not read Spotify user profile.")

    playlist_name = f"{PLAYLIST_NAME_PREFIX}{name_suffix}".strip()[:100] or "MixID Tracklist"
    playlist = sp.user_playlist_create(
        user=user["id"],
        name=playlist_name,
        public=True,
        description=PLAYLIST_DESCRIPTION,
    )

    track_uris: list[str] = []
    unmatched: list[str] = []
    for t in tracks:
        artist = (t.get("artist") or "").strip()
        title = (t.get("title") or "").strip()
        if not title:
            continue
        query = f'track:"{title}" artist:"{artist}"' if artist else f'track:"{title}"'
        try:
            results = sp.search(q=query, type="track", limit=1)
        except Exception as e:
            log.warning("Spotify search failed for %r: %s", query, e)
            unmatched.append(f"{artist} - {title}".strip(" -"))
            continue
        items = (results.get("tracks") or {}).get("items") or []
        if not items:
            try:
                loose = sp.search(q=f"{artist} {title}".strip(), type="track", limit=1)
                items = (loose.get("tracks") or {}).get("items") or []
            except Exception:
                items = []
        if not items:
            unmatched.append(f"{artist} - {title}".strip(" -"))
            continue
        track_uris.append(items[0]["uri"])

    added = 0
    for i in range(0, len(track_uris), 100):
        chunk = track_uris[i : i + 100]
        sp.playlist_add_items(playlist["id"], chunk)
        added += len(chunk)

    return PlaylistResult(
        playlist_id=playlist["id"],
        playlist_url=(playlist.get("external_urls") or {}).get("spotify", ""),
        tracks_added=added,
        tracks_unmatched=unmatched,
    )
